// ====================================================================== 
// == DO NOT MODIFY THIS FILE BY HAND - IT IS AUTO GENERATED BY CMAKE! ==
// ======================================================================
//
// doctest.rs - the lightest feature-rich C++ single-header testing framework for unit tests and TDD
//
// Copyright (c) 2016-2021 Viktor Kirilov
//
// Distributed under the MIT Software License
// See accompanying file LICENSE.txt or copy at
// https://opensource.org/licenses/MIT
//
// The documentation can be found at the library's page:
// https://github.com/onqtam/doctest/blob/master/doc/markdown/readme.md
//
// =================================================================================================
// =================================================================================================
// =================================================================================================
//
// The library is heavily influenced by Catch - https://github.com/catchorg/Catch2
// which uses the Boost Software License - Version 1.0
// see here - https://github.com/catchorg/Catch2/blob/master/LICENSE.txt
//
// The concept of subcases (sections in Catch) and expression decomposition are from there.
// Some parts of the code are taken directly:
// - stringification - the detection of "ostream& operator<<(ostream&, const T&)" and StringMaker<>
// - the Approx() helper class for floating point comparison
// - colors in the console
// - breaking into a debugger
// - signal / SEH handling
// - timer
// - XmlWriter class - thanks to Phil Nash for allowing the direct reuse (AKA copy/paste)
//
// The expression decomposing templates are taken from lest - https://github.com/martinmoene/lest
// which uses the Boost Software License - Version 1.0
// see here - https://github.com/martinmoene/lest/blob/master/LICENSE.txt
//
// =================================================================================================
// =================================================================================================
// =================================================================================================

use std::fmt;

#[cfg(target_os = "windows")]
mod platform {
    pub const WINDOWS: bool = true;
    pub const POSIX: bool = false;
}

#[cfg(not(target_os = "windows"))]
mod platform {
    pub const WINDOWS: bool = false;
    pub const POSIX: bool = true;
}

fn is_debugger_active() -> bool {
    false
}

#[derive(Debug)]
struct String {
    data: std::string::String,
}

impl String {
    fn new() -> Self {
        Self { data: std::string::String::new() }
    }

    fn from_str(s: &str) -> Self {
        Self { data: s.to_string() }
    }
}

impl fmt::Display for String {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.data)
    }
}

impl PartialEq for String {
    fn eq(&self, other: &Self) -> bool {
        self.data.eq(&other.data)
    }
}

impl Eq for String {}

#[derive(Debug)]
enum AssertType {
    Warn,
    Check,
    Require,
    WarnFalse,
    CheckFalse,
    RequireFalse,
    WarnThrows,
    CheckThrows,
    RequireThrows,
    WarnThrowsAs,
    CheckThrowsAs,
    RequireThrowsAs,
    WarnNothrow,
    CheckNothrow,
    RequireNothrow,
}

struct Approx {
    value: f64,
    epsilon: f64,
    scale: f64,
}

impl Approx {
    fn new(value: f64) -> Self {
        Self {
            value,
            epsilon: 1e-12,
            scale: 1.0,
        }
    }

    fn epsilon(mut self, epsilon: f64) -> Self {
        self.epsilon = epsilon;
        self
    }

    fn scale(mut self, scale: f64) -> Self {
        self.scale = scale;
        self
    }
}

impl PartialEq<f64> for Approx {
    fn eq(&self, other: &f64) -> bool {
        let diff = (self.value - other).abs();
        diff < self.epsilon * (self.scale + self.value.abs().max(other.abs()))
    }
}

impl PartialEq<Approx> for f64 {
    fn eq(&self, other: &Approx) -> bool {
        other.eq(self)
    }
}

struct ContextOptions {
    // Command line parameters
    order_by: String,
    rand_seed: u32,
    abort_after: i32,
    duration: bool,
    no_throw: bool,
    no_exitcode: bool,
    no_run: bool,
    no_version: bool,
    no_colors: bool,
    gnu_file_line: bool,
    force_colors: bool,

    // Internal runtime data
    num_asserts: i32,
    num_asserts_failed: i32,
    num_test_cases: i32,
    num_test_cases_passing_filters: i32,
    num_test_cases_failed: i32,
}

impl ContextOptions {
    fn new() -> Self {
        Self {
            order_by: String::new(),
            rand_seed: 0,
            abort_after: 0,
            duration: false,
            no_throw: false,
            no_exitcode: false,
            no_run: false,
            no_version: false,
            no_colors: false,
            gnu_file_line: false,
            force_colors: false,

            num_asserts: 0,
            num_asserts_failed: 0,
            num_test_cases: 0,
            num_test_cases_passing_filters: 0,
            num_test_cases_failed: 0,
        }
    }
}

fn main() {
    let mut context_options = ContextOptions::new();
}