[project]
name = "code-translation-engine"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "agno[os]>=2.5.17",
    "fastapi[standard]>=0.136.0",
    "pydantic>=2.13.2",
]

[dependency-groups]
dev = [
    "ipykernel>=7.2.0",
    "mypy>=1.20.1",
]
