// ======================================================================
// == DO NOT MODIFY THIS FILE BY HAND - IT IS AUTO GENERATED BY CMAKE! ==
// ======================================================================
//
// doctest.rs - the lightest feature-rich Rust single-file testing framework for unit tests and TDD
//

use std::fmt::{Display, Formatter};
use std::str;

const DOCTEST_VERSION_MAJOR: i32 = 2;
const DOCTEST_VERSION_MINOR: i32 = 4;
const DOCTEST_VERSION_PATCH: i32 = 6;
const DOCTEST_VERSION_STR: &'static str = "2.4.6";

const DOCTEST_VERSION: i32 = DOCTEST_VERSION_MAJOR * 10000 + DOCTEST_VERSION_MINOR * 100 + DOCTEST_VERSION_PATCH;

#[cfg(windows)]
fn get_compiler_version_msvc(m: i32, mf: i32) -> i32 {
    if m == mf / 10000 {
        return DOCTEST_COMPILER(m / 100, m % 100, mf % 10000);
    } else {
        return DOCTEST_COMPILER(m / 100, (mf / 100000) % 100, mf % 100000);
    }
    fn DOCTEST_COMPILER(major: i32, minor: i32, patch: i32) -> i32 {
        major * 10000000 + minor * 100000 + patch
    }
}

fn get_compiler_version_gcc_or_clang(
    major: Option<i32>,
    minor: Option<i32>,
    patch: Option<i32>,
    intel: Option<i32>,
) -> i32 {
    if (cfg!(target_os = "linux") || cfg!(target_os = "macos")) && intel.is_none() {
        if major.is_some() && minor.is_some() && patch.is_some() {
            return DOCTEST_COMPILER(major.unwrap(), minor.unwrap(), patch.unwrap());
        } else {
            return 0;
        }
    } else {
        return 0;
    }
    fn DOCTEST_COMPILER(major: i32, minor: i32, patch: i32) -> i32 {
        major * 10000000 + minor * 100000 + patch
    }
}

// Compiler macros
#[cfg(windows)]
const DOCTEST_MSVC: i32 = get_compiler_version_msvc(0, 0);

#[cfg(not(windows))]
const DOCTEST_MSVC: i32 = 0;

#[cfg(any(target_os = "linux", target_os = "macos"))]
fn doctest_clang_version() -> i32 {
    get_compiler_version_gcc_or_clang(
        option_env!("clang_major").and_then(|v| v.parse().ok()),
        option_env!("clang_minor").and_then(|v| v.parse().ok()),
        option_env!("clang_patchlevel").and_then(|v| v.parse().ok()),
        None,
    )
}

#[cfg(any(target_os = "linux", target_os = "macos"))]
fn doctest_gcc_version() -> i32 {
    get_compiler_version_gcc_or_clang(
        option_env!("GNU_major").and_then(|v| v.parse().ok()),
        option_env!("GNU_minor").and_then(|v| v.parse().ok()),
        option_env!("GNU_patchlevel").and_then(|v| v.parse().ok()),
        option_env!("INTEL_COMPILER").and_then(|v| v.parse().ok()),
    )
}

#[cfg(not(any(target_os = "linux", target_os = "macos")))]
const DOCTEST_CLANG: i32 = 0;

#[cfg(target_os = "linux")]
const DOCTEST_GCC: i32 = 0;

struct TestCase; // Dummy struct for the example

macro_rules! DOCTEST_DEFINE_DECORATOR {
    ($name:ident, $type:ty, $def:expr) => {
        struct $name {
            data: $type,
        }

        impl $name {
            fn fill(&self, _: &mut TestCase) {
                let _ = self.data;
            }

            fn new(data: $type) -> Self {
                Self { data }
            }
        }

        impl Default for $name {
            fn default() -> Self {
                $name { data: $def }
            }
        }
    };
}

// String conversion of primitive types
fn to_string<T>(value: T) -> String
where
    T: Display,
{
    value.to_string()
}

DOCTEST_DEFINE_DECORATOR!(test_suite, &'static str, "");
DOCTEST_DEFINE_DECORATOR!(description, &'static str, "");
DOCTEST_DEFINE_DECORATOR!(skip, bool, true);
DOCTEST_DEFINE_DECORATOR!(no_breaks, bool, true);
DOCTEST_DEFINE_DECORATOR!(no_output, bool, true);
DOCTEST_DEFINE_DECORATOR!(timeout, f64, 0.0);
DOCTEST_DEFINE_DECORATOR!(may_fail, bool, true);
DOCTEST_DEFINE_DECORATOR!(should_fail, bool, true);
DOCTEST_DEFINE_DECORATOR!(expected_failures, i32, 0);

unsafe fn raise_signal(signal: i32) {
    extern "C" {
        fn raise(signal: i32) -> i32;
    }
    raise(signal);
}

fn main() {
    #[cfg(target_os = "linux")]
    unsafe {
        const SIGINT: i32 = 2;
        raise_signal(SIGINT);
    }
}