// ======================================================================
// == DO NOT MODIFY THIS FILE BY HAND - IT IS AUTO GENERATED BY CMAKE! ==
// ======================================================================
//
// doctest.rs - the lightest feature-rich Rust single-header testing framework for unit tests and TDD
//
// Copyright (c) 2016-2021 Viktor Kirilov
//
// Distributed under the MIT Software License
// See accompanying file LICENSE.txt or copy at
// https://opensource.org/licenses/MIT
//
// The documentation can be found at the library's page:
// https://github.com/onqtam/doctest/blob/master/doc/markdown/readme.md
//
// =================================================================================================
// =================================================================================================
// =================================================================================================
//
// The library is heavily influenced by Catch - https://github.com/catchorg/Catch2
// which uses the Boost Software License - Version 1.0
// see here - https://github.com/catchorg/Catch2/blob/master/LICENSE.txt
//
// The concept of subcases (sections in Catch) and expression decomposition are from there.
// Some parts of the code are taken directly:
// - stringification - the detection of "pub fn std::fmt::Display for T" and StringMaker<>
// - the Approx() helper class for floating point comparison
// - colors in the console
// - breaking into a debugger
// - signal handling
// - timer
// - XmlWriter class - thanks to Phil Nash for allowing the direct reuse
//
// The expression decomposing templates are taken from lest - https://github.com/martinmoene/lest
// which uses the Boost Software License - Version 1.0
// see here - https://github.com/martinmoene/lest/blob/master/LICENSE.txt
//
// =================================================================================================
// =================================================================================================
// =================================================================================================

// =================================================================================================
// == VERSION ======================================================================================
// =================================================================================================

const DOCTEST_VERSION_MAJOR: u32 = 2;
const DOCTEST_VERSION_MINOR: u32 = 4;
const DOCTEST_VERSION_PATCH: u32 = 6;
const DOCTEST_VERSION_STR: &str = "2.4.6";

const DOCTEST_VERSION: u32 = DOCTEST_VERSION_MAJOR * 10000 + DOCTEST_VERSION_MINOR * 100 + DOCTEST_VERSION_PATCH;

// =================================================================================================
// == COMPILER VERSION =============================================================================
// =================================================================================================

// ideas for the version stuff are taken from here: https://github.com/cxxstuff/cxx_detect

const fn DOCTEST_COMPILER(major: u32, minor: u32, patch: u32) -> u32 {
    major * 10000000 + minor * 100000 + patch
}

// =================================================================================================
// == FEATURE DETECTION END ========================================================================
// =================================================================================================

// internal macros for string concatenation and anonymous variable name generation
macro_rules! DOCTEST_CAT_IMPL {
    ($s1:expr, $s2:expr) => {
        concat!($s1, $s2)
    };
}

macro_rules! DOCTEST_CAT {
    ($s1:expr, $s2:expr) => {
        DOCTEST_CAT_IMPL!($s1, $s2)
    };
}

macro_rules! DOCTEST_ANONYMOUS {
    ($x:expr) => {
        DOCTEST_CAT!($x, std::line!())
    };
}

macro_rules! DOCTEST_TOSTR {
    ($x:expr) => {
        stringify!($x)
    };
}

#[cfg(target_os = "macos")]
const DOCTEST_PLATFORM: &str = "MAC";
#[cfg(target_os = "ios")]
const DOCTEST_PLATFORM: &str = "IPHONE";
#[cfg(windows)]
const DOCTEST_PLATFORM: &str = "WINDOWS";
#[cfg(unix)]
const DOCTEST_PLATFORM: &str = "LINUX";

#[cfg(doctest_config_use_std_headers)]
mod std {
    pub use std::println;
}

#[cfg(doctest_config_use_std_headers)]
use std::{fmt, io, time};

#[derive(Clone)]
struct String(pub std::string::String);

impl String {
    pub fn new() -> Self {
        String(std::string::String::new())
    }

    pub fn from_str(s: &str) -> Self {
        String(s.to_string())
    }

    pub fn len(&self) -> usize {
        self.0.len()
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }
}

use std::fmt;
impl fmt::Display for String {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

use std::result;
use std::option;
use std::error::Error;

use std::io;

type Result<T> = result::Result<T, Box<dyn Error>>;
type Option<T> = option::Option<T>;

pub struct ContextOptions {
    pub cout: Option<io::Stdout>,
    pub cerr: Option<io::Stderr>,
    pub binary_name: String,
    pub current_test: Option<TestCase>,
    pub out: String,
    pub order_by: String,
    pub rand_seed: u32,
    pub first: u32,
    pub last: u32,
    pub abort_after: i32,
    pub subcase_filter_levels: i32,
    pub success: bool,
    pub case_sensitive: bool,
    pub exit: bool,
    pub duration: bool,
    pub no_throw: bool,
    pub no_exitcode: bool,
    pub no_run: bool,
    pub no_version: bool,
    pub no_colors: bool,
    pub force_colors: bool,
    pub no_breaks: bool,
    pub no_skip: bool,
    pub gnu_file_line: bool,
    pub no_path_in_filenames: bool,
    pub no_line_numbers: bool,
    pub no_debug_output: bool,
    pub no_skipped_summary: bool,
    pub no_time_in_output: bool,
    pub help: bool,
    pub version: bool,
    pub count: bool,
    pub list_test_cases: bool,
    pub list_test_suites: bool,
    pub list_reporters: bool,
}

pub struct TestCaseData {
    pub file: String,
    pub line: u32,
    pub name: String,
    pub test_suite: String,
    pub description: String,
    pub skip: bool,
    pub no_breaks: bool,
    pub no_output: bool,
    pub may_fail: bool,
    pub should_fail: bool,
    pub expected_failures: i32,
    pub timeout: f64,
}

pub struct TestCase {
    pub data: TestCaseData,
    pub test: Box<dyn Fn()>,
    pub type_name: Option<String>,
    pub template_id: i32,
    pub full_name: Option<String>,
}

impl TestCase {
    pub fn new(
        test: Box<dyn Fn()>,
        file: &str,
        line: u32,
        test_suite: &TestSuite,
        type_name: Option<&str>,
        template_id: i32,
    ) -> Self {
        let data = TestCaseData {
            file: String::from_str(file),
            line,
            name: String::new(),
            test_suite: test_suite.name.clone(),
            description: test_suite.description.clone(),
            skip: test_suite.skip,
            no_breaks: test_suite.no_breaks,
            no_output: test_suite.no_output,
            may_fail: test_suite.may_fail,
            should_fail: test_suite.should_fail,
            expected_failures: test_suite.expected_failures,
            timeout: test_suite.timeout,
        };
        Self {
            data,
            test,
            type_name: type_name.map(String::from_str),
            template_id,
            full_name: None,
        }
    }

    pub fn with_name(mut self, name: &str) -> Self {
        self.data.name = String::from_str(name);
        if let Some(type_name) = &self.type_name {
            self.full_name = Some(String(self.data.name.as_str().to_string() + type_name.as_str()));
            self.data.name = self.full_name.clone().unwrap();
        }
        self
    }
}

pub struct TestSuite {
    pub name: String,
    pub description: String,
    pub skip: bool,
    pub no_breaks: bool,
    pub no_output: bool,
    pub may_fail: bool,
    pub should_fail: bool,
    pub expected_failures: i32,
    pub timeout: f64,
}

impl Default for TestSuite {
    fn default() -> Self {
        Self {
            name: String::new(),
            description: String::new(),
            skip: false,
            no_breaks: false,
            no_output: false,
            may_fail: false,
            should_fail: false,
            expected_failures: 0,
            timeout: 0.0,
        }
    }
}

impl TestSuite {
    pub fn with_name(mut self, name: &str) -> Self {
        self.name = String::from_str(name);
        self
    }
}

impl From<&str> for String {
    fn from(s: &str) -> Self {
        String::from_str(s)
    }
}

impl From<&str> for TestSuite {
    fn from(s: &str) -> Self {
        Self::default().with_name(s)
    }
}

impl Clone for TestCase {
    fn clone(&self) -> Self {
        fn clone_box(f: &Box<dyn Fn()>) -> Box<dyn Fn()> {
            Box::new(move || f())
        }

        Self {
            data: self.data.clone(),
            test: clone_box(&self.test),
            type_name: self.type_name.clone(),
            template_id: self.template_id,
            full_name: self.full_name.clone(),
        }
    }
}

impl Clone for TestCaseData {
    fn clone(&self) -> Self {
        Self {
            file: self.file.clone(),
            line: self.line,
            name: self.name.clone(),
            test_suite: self.test_suite.clone(),
            description: self.description.clone(),
            skip: self.skip,
            no_breaks: self.no_breaks,
            no_output: self.no_output,
            may_fail: self.may_fail,
            should_fail: self.should_fail,
            expected_failures: self.expected_failures,
            timeout: self.timeout,
        }
    }
}

fn main() {
    println!("This is the main function.");
}